# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [7]:
!pip install nbformat

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
arr=np.array([1,2,3,4,5])
print(arr.nbytes)

40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
arr = np.zeros(10)
arr[4] = 1

print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
arr = np.arange(10, 50)
arr = arr[::-1]
print(arr)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
arr = np.arange(9).reshape(3, 3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
arr = np.random.random((3, 3, 3))
print(arr)


[[[0.51809028 0.05610465 0.53557384]
  [0.83848817 0.82950106 0.61304821]
  [0.17381469 0.4313463  0.83274121]]

 [[0.64063341 0.04018749 0.02740045]
  [0.18215689 0.46042241 0.42830463]
  [0.1370886  0.96126008 0.88971489]]

 [[0.48729582 0.87008736 0.15849781]
  [0.32504582 0.48241287 0.52419527]
  [0.27248704 0.47218434 0.75064657]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
arr = np.random.random((10, 10))
print("Min:", arr.min(), "Max:", arr.max())


Min: 0.016851003868954995 Max: 0.9846479115209118


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
arr = np.random.random(30)
print("Mean:", arr.mean())


Mean: 0.5000548125249212


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
arr = np.ones((3, 3))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [29]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
arr = np.diag(np.arange(1, 5), k=-1)
print(arr)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
print(np.unravel_index(100, (6, 7, 8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
arr = np.tile([[0, 1], [1, 0]], (4, 4))
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [34]:
arr = np.random.random((5, 5))
arr = (arr - arr.min()) / (arr.max() - arr.min())
print(arr)


[[0.3227102  0.67750986 0.75708503 0.18585462 0.5127887 ]
 [0.08747606 0.77286014 1.         0.12878503 0.52090155]
 [0.06131677 0.85969467 0.19185052 0.97141943 0.6098651 ]
 [0.25922239 0.29131268 0.         0.04429994 0.54096276]
 [0.30932345 0.44381145 0.17037076 0.14409975 0.61691986]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [36]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
result = np.dot(A, B)
print(result)


[[0.67865637 0.41893567]
 [0.89691395 0.83000969]
 [0.51494067 0.31468628]
 [1.53810062 1.00862243]
 [0.51652553 0.52669017]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [37]:
arr = np.arange(10)
arr[(arr >= 3) & (arr <= 8)] *= -1
print(arr)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [38]:
print(sum(range(5), -1))  # 9
from numpy import *
print(sum(range(5), -1))  # [0 1 2 3 4]


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
Z = np.arange(5)
print(Z ** Z)  # Legal
print(2 << Z >> 2)  # Legal
print(Z < -Z)  # Legal
print(1j * Z)  # Legal
print(Z / 1 / 1)  # Legal
# print(Z < Z > Z)  # Illegal


[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
print(np.array(0) / np.array(0))  # nan
print(np.array(0) // np.array(0))  # RuntimeWarning
print(np.array([np.nan]).astype(int).astype(float))  # [-9.22337204e+18] (system-dependent)


nan
0
[-9.22337204e+18]


<ipython-input-40-bc2611449961>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))  # nan
<ipython-input-40-bc2611449961>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # RuntimeWarning
<ipython-input-40-bc2611449961>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))  # [-9.22337204e+18] (system-dependent)


#### 29. How to round away from zero a float array ? (★☆☆)

In [41]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2))


[3 4 5]


#### 30. How to find common values between two arrays? (★☆☆)

In [42]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(arr1, arr2))


[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [43]:
import warnings
warnings.filterwarnings("ignore")


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
print(np.sqrt(-1) == np.emath.sqrt(-1))


False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)


2025-03-08 2025-03-09 2025-03-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [46]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [48]:
A = np.ones(3)
B = np.ones(3) * 2
np.add(A, B, out=A)
np.divide(A, -2, out=A)
np.multiply(A, A, out=A)
print(A)


[2.25 2.25 2.25]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [49]:
arr = np.random.uniform(0, 10, 5)
print(arr.astype(int))
print(np.floor(arr))
print(np.ceil(arr) - 1)
print(np.trunc(arr))


[5 2 7 8 1]
[5. 2. 7. 8. 1.]
[5. 2. 7. 8. 1.]
[5. 2. 7. 8. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [50]:
arr = np.tile(np.arange(5), (5, 1))
print(arr)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [51]:
def generate_numbers():
    for i in range(10):
        yield i
numbers_array = np.array(list(generate_numbers()))

print(numbers_array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [52]:
vector = np.random.uniform(0, 1, 10)
print(vector)


[0.16869094 0.25218799 0.4192136  0.21057599 0.52526765 0.25529586
 0.62162235 0.77327959 0.54456097 0.97762812]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [58]:
arr = np.random.randint(1, 11, 10)
arr
arr.sort()
print(arr)

[1 2 2 5 6 6 8 9 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [59]:
arr = np.array([1, 2, 3, 4, 5])
result = sum(arr)
print(result)


15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [60]:
a=np.random.random(2)
b=np.random.random(2)
print(np.array_equal(a,b))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False

print(arr)


[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [62]:
cartesian = np.random.rand(10, 2)  # Random 10x2 matrix
x, y = cartesian[:, 0], cartesian[:, 1]

r = np.sqrt(x**2 + y**2)  # Radius
theta = np.arctan2(y, x)  # Angle

polar = np.column_stack((r, theta))  # Stack r and theta
print(polar)

[[0.75978919 1.02793221]
 [0.23013309 0.90676906]
 [0.68853915 1.35709552]
 [1.09823816 1.14302454]
 [1.16737035 0.94965155]
 [0.65885523 1.34019157]
 [1.13456473 1.04716646]
 [0.99279787 1.56948824]
 [0.71495248 0.42421132]
 [0.79231201 1.4832315 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [63]:
arr = np.random.rand(10)  # Random vector
arr[arr.argmax()] = 0  # Replace max with 0
print(arr)


[0.82089187 0.         0.05960721 0.30802005 0.39275656 0.94343206
 0.78055744 0.00648051 0.57598198 0.74613049]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [64]:
grid_x, grid_y = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
structured_array = np.core.records.fromarrays([grid_x.ravel(), grid_y.ravel()], names='x, y')

print(structured_array)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [65]:
X = np.random.rand(5)
Y = np.random.rand(5)

C = 1 / (X[:, None] - Y[None, :])
print(C)


[[ -9.67159744  23.13788162  -5.28008755  -2.14328084  -2.65692208]
 [ 49.95041026   6.00115607 -15.15716294  -2.91410086  -3.9531947 ]
 [ -4.45878424 -12.8763635   -3.22298223  -1.70225729  -2.01103574]
 [  5.46149059   3.03292329  10.29813795  -5.55312818 -11.12599203]
 [ -3.54347019  -7.3749289   -2.71588211  -1.54945526  -1.80118825]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [66]:
types = [np.int32, np.int64, np.float32, np.float64]
for dtype in types:
    print(f"{dtype}: min={np.iinfo(dtype).min if np.issubdtype(dtype, np.integer) else np.finfo(dtype).min}, "
          f"max={np.iinfo(dtype).max if np.issubdtype(dtype, np.integer) else np.finfo(dtype).max}")


<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [67]:
np.set_printoptions(threshold=np.inf)  # Force full array printing
arr = np.arange(100)  # Large array
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [68]:
arr = np.random.rand(10)
scalar = 0.5
closest = arr[np.abs(arr - scalar).argmin()]
print(f"Array: {arr}\nClosest value to {scalar}: {closest}")


Array: [0.89339261 0.69755095 0.56407734 0.21247818 0.80267147 0.89681093
 0.94491399 0.02403636 0.94154604 0.95698723]
Closest value to 0.5: 0.564077338781619


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [70]:
import numpy as np

dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]
structured_array = np.array([((1.0, 2.0), (255, 0, 0)), ((3.0, 4.0), (0, 255, 0))], dtype=dtype)

print(structured_array)


[((1., 2.), (255,   0, 0)) ((3., 4.), (  0, 255, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import numpy as np

# Generate random 100x2 coordinates
coords = np.random.rand(100, 2)

# Compute pairwise Euclidean distance matrix using broadcasting
dists = np.sqrt(((coords[:, np.newaxis, :] - coords[np.newaxis, :, :]) ** 2).sum(axis=2))

print(dists)



#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [73]:
arr = np.random.rand(5).astype(np.float32)  # Float32 array
arr = arr.view(np.int32)  # Convert to int32 in place

print(arr)


[1058796952 1051918634 1059050124 1028866766 1050605896]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [76]:
arr = np.array([10, 20, 30, 40])
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [77]:
from scipy.stats import multivariate_normal

x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
pos = np.dstack((x, y))
rv = multivariate_normal([0, 0], [[1, 0], [0, 1]])
gaussian = rv.pdf(pos)

print(gaussian)

[[0.05854983 0.07133657 0.08272793 0.09131569 0.09593831 0.09593831
  0.09131569 0.08272793 0.07133657 0.05854983]
 [0.07133657 0.08691581 0.10079493 0.11125819 0.11689034 0.11689034
  0.11125819 0.10079493 0.08691581 0.07133657]
 [0.08272793 0.10079493 0.11689034 0.12902442 0.13555594 0.13555594
  0.12902442 0.11689034 0.10079493 0.08272793]
 [0.09131569 0.11125819 0.12902442 0.1424181  0.14962764 0.14962764
  0.1424181  0.12902442 0.11125819 0.09131569]
 [0.09593831 0.11689034 0.13555594 0.14962764 0.15720215 0.15720215
  0.14962764 0.13555594 0.11689034 0.09593831]
 [0.09593831 0.11689034 0.13555594 0.14962764 0.15720215 0.15720215
  0.14962764 0.13555594 0.11689034 0.09593831]
 [0.09131569 0.11125819 0.12902442 0.1424181  0.14962764 0.14962764
  0.1424181  0.12902442 0.11125819 0.09131569]
 [0.08272793 0.10079493 0.11689034 0.12902442 0.13555594 0.13555594
  0.12902442 0.11689034 0.10079493 0.08272793]
 [0.07133657 0.08691581 0.10079493 0.11125819 0.11689034 0.11689034
  0.11125819

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [78]:
arr = np.zeros((10, 10))
p = 5
indices = np.random.choice(arr.size, p, replace=False)
arr.flat[indices] = 1

print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [79]:
matrix = np.random.rand(5, 5)
result = matrix - matrix.mean(axis=1, keepdims=True)

print(result)


[[-0.35186773  0.2174645  -0.19248871  0.51046215 -0.18357022]
 [ 0.49692362 -0.1615111  -0.25899919  0.04002855 -0.11644188]
 [-0.10669695 -0.09088109  0.37421201 -0.14084999 -0.03578397]
 [-0.15367246 -0.26394172 -0.07768012  0.12041365  0.37488065]
 [-0.02510343  0.06201673 -0.04678941 -0.24580469  0.2556808 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [80]:
arr = np.random.randint(0, 100, (5, 3))
n = 1  # Sort by second column
sorted_arr = arr[arr[:, n].argsort()]

print(sorted_arr)


[[66 30 51]
 [ 1 79 71]
 [10 81 31]
 [43 85 48]
 [95 92 21]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [81]:
arr = np.random.randint(0, 2, (4, 5))  # Example array
null_columns = np.all(arr == 0, axis=0)

print(null_columns)  # True means the column is all zeros


[False False False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [82]:
arr = np.random.rand(10)
scalar = 0.5
nearest = arr[np.abs(arr - scalar).argmin()]

print(nearest)


0.5083175604111845


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [83]:
a = np.array([[1, 2, 3]])  # Shape (1,3)
b = np.array([[4], [5], [6]])  # Shape (3,1)

it = np.nditer([a, b, None])
for x, y, res in it:
    res[...] = x + y
print(it.operands[2])


[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [84]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="Unnamed"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

arr = NamedArray([1, 2, 3], name="MyArray")
print(arr.name, arr)


MyArray [1 2 3]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [85]:
import numpy as np

X = np.zeros(10, dtype=int)  # Initialize a vector of zeros
indices = np.array([1, 3, 3, 7, 8, 1])  # Indices where we add 1

np.add.at(X, indices, 1)  # Adds 1 at the specified indices (handling repeats)
print(X)


[0 2 0 2 0 0 0 1 1 0]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [86]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 1, 0])  # Index list
F = np.zeros(3)  # Target array

np.add.at(F, I, X)
print(F)  # Accumulated values


[6. 6. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [87]:
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)  # Random image
unique_colors = np.unique(image.reshape(-1, 3), axis=0)  # Find unique colors
print(len(unique_colors))  # Number of unique colors


9996


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [88]:
A = np.random.rand(3, 4, 5, 6)
result = A.sum(axis=(-2, -1))  # Summing over last two axes
print(result.shape)  # Expected shape (3, 4)


(3, 4)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [89]:
D = np.random.rand(10)
S = np.array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3])  # Subset indices
means = np.bincount(S, weights=D) / np.bincount(S)  # Compute means per subset
print(means)


[0.78284953 0.59647873 0.63480435 0.42768648]


#### 69. How to get the diagonal of a dot product? (★★★)

In [90]:
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)

diagonal = np.einsum("ij,ji->i", A, B)  # Efficient way to compute diagonal
print(diagonal)


[1.50762121 0.20175226 0.6343635  1.02377232]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [91]:
vec = np.array([1, 2, 3, 4, 5])
new_vec = np.zeros(len(vec) * 4 - 3, dtype=int)  # Extra spaces for zeros
new_vec[::4] = vec  # Place original elements at every 4th position
print(new_vec)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [93]:
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5, 1)  # Reshape to (5,5,1) for broadcasting
result = A * B
print(result.shape)  # Should be (5,5,3)



(5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [94]:
A = np.arange(25).reshape(5, 5)
A[[0, 2]] = A[[2, 0]]  # Swap row 0 and row 2
print(A)


[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [95]:
triangles = np.random.randint(0, 100, (10, 3, 2))  # 10 triangles with 3 vertices each
edges = np.sort(np.concatenate([triangles[:, [0, 1]], triangles[:, [1, 2]], triangles[:, [2, 0]]]), axis=1)
unique_edges = np.unique(edges, axis=0)
print(unique_edges)


[[[ 0 11]
  [ 3 99]]

 [[ 0 35]
  [21 99]]

 [[ 3 11]
  [21 35]]

 [[ 4 23]
  [16 67]]

 [[ 4 59]
  [35 67]]

 [[ 6  7]
  [11 57]]

 [[ 6  7]
  [11 74]]

 [[ 6 57]
  [ 6 74]]

 [[ 7 14]
  [34 56]]

 [[ 7 14]
  [48 58]]

 [[ 8  0]
  [26 95]]

 [[ 8  0]
  [77  7]]

 [[10 57]
  [37 73]]

 [[10 73]
  [75 99]]

 [[15 32]
  [61 48]]

 [[15 48]
  [74 91]]

 [[16 23]
  [35 59]]

 [[25 45]
  [80 53]]

 [[25 51]
  [94 53]]

 [[26  7]
  [77 95]]

 [[31 57]
  [32 59]]

 [[31 57]
  [76 65]]

 [[32 59]
  [76 65]]

 [[34 56]
  [48 58]]

 [[37 57]
  [75 99]]

 [[61 32]
  [74 91]]

 [[66  1]
  [94 27]]

 [[66 10]
  [95 27]]

 [[80 45]
  [94 51]]

 [[94  1]
  [95 10]]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [96]:
C = np.array([3, 2, 0, 4])  # Example bincount
A = np.repeat(np.arange(len(C)), C)  # Expands elements based on counts
print(A)  # Resulting array


[0 0 0 1 1 3 3 3 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [97]:
X = np.arange(10)
window_size = 3
averages = np.convolve(X, np.ones(window_size) / window_size, mode='valid')
print(averages)


[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [98]:
import numpy as np

Z = np.arange(10)  # Example 1D array
window_size = 3
result = np.lib.stride_tricks.sliding_window_view(Z, window_size)
print(result)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [101]:
Z = np.array([True, False, True])
Z = ~Z  # Negate boolean
print(Z)

F = np.array([1.0, -2.5, 3.6])
F *= -1  # Change sign of float
print(F)


[False  True False]
[-1.   2.5 -3.6]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [102]:
P0 = np.random.rand(5, 2)  # Random 2D start points
P1 = np.random.rand(5, 2)  # Random 2D end points
p = np.random.rand(2)  # Random 2D point

def point_to_line_dist(P0, P1, p):
    num = np.abs(np.cross(P1 - P0, P0 - p))
    denom = np.linalg.norm(P1 - P0, axis=1)
    return num / denom

distances = point_to_line_dist(P0, P1, p)
print(distances)


[0.17973698 0.30741036 0.47752883 0.27699139 0.41879178]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [103]:
P = np.random.rand(5, 2)  # Random set of points

distances = np.array([point_to_line_dist(P0, P1, p) for p in P])
print(distances)


[[0.20306324 0.25471468 0.6398821  0.84734358 0.1490225 ]
 [0.49357133 0.16664225 0.08790045 0.42185154 0.03337621]
 [0.74198355 0.15807658 0.21178351 0.07797599 0.2957725 ]
 [0.61349318 0.01819669 0.13472054 0.23744933 0.15308405]
 [0.58433835 0.38425528 0.06671802 0.01303657 0.51117819]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [104]:
def extract_subarray(A, center, shape, fill_value=0):
    padded = np.pad(A, [(s//2, s//2) for s in shape], constant_values=fill_value)
    slices = tuple(slice(c, c + s) for c, s in zip(center, shape))
    return padded[slices]

A = np.random.randint(0, 10, (5, 5))
subarray = extract_subarray(A, (2, 2), (3, 3))
print(subarray)


[[4 1 5]
 [4 7 2]
 [3 3 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [105]:
Z = np.arange(1, 15)
window_size = 4
R = np.lib.stride_tricks.sliding_window_view(Z, window_size)
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [106]:
M = np.random.randint(0, 10, (5, 5))
rank = np.linalg.matrix_rank(M)
print(rank)


5


#### 83. How to find the most frequent value in an array?

In [107]:
Z = np.random.randint(0, 10, 100)
most_frequent = np.bincount(Z).argmax()
print(most_frequent)


0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [108]:
A = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.sliding_window_view(A, (3, 3))
print(blocks.shape)  # Should be (8, 8, 3, 3)


(8, 8, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [109]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

Z = np.zeros((5, 5)).view(SymmetricArray)
Z[1, 3] = 5
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [110]:
p, n = 3, 4
M = np.random.rand(p, n, n)
V = np.random.rand(p, n, 1)

result = np.einsum("pij,pjk->ik", M, V)
print(result.shape)  # Should be (n,1)


(4, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [111]:
A = np.random.randint(0, 10, (16, 16))
block_size = 4
block_sums = A.reshape(16//block_size, block_size, 16//block_size, block_size).sum(axis=(1,3))
print(block_sums)


[[ 74  80  56  77]
 [ 84  57  64  74]
 [ 81  76 101  76]
 [ 57  79  78  70]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [112]:
def game_of_life_step(board):
    neighbors = sum(np.roll(np.roll(board, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1) if (i, j) != (0, 0))
    return (neighbors == 3) | (board & (neighbors == 2))

board = np.random.choice([0, 1], (10, 10))
new_board = game_of_life_step(board)
print(new_board)


[[0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 1 0 0]
 [1 1 1 0 1 0 0 0 0 1]]


#### 89. How to get the n largest values of an array (★★★)

In [113]:
Z = np.random.randint(0, 100, 10)
n = 3
largest_values = np.sort(Z)[-n:]
print(largest_values)


[85 89 97]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [114]:
arrays = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]
cartesian_product = np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))
print(cartesian_product)


[[1 4 6]
 [1 5 6]
 [2 4 6]
 [2 5 6]
 [3 4 6]
 [3 5 6]
 [1 4 7]
 [1 5 7]
 [2 4 7]
 [2 5 7]
 [3 4 7]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [115]:
import numpy as np

Z = np.array([(1, 2.0, 'A'), (2, 3.0, 'B'), (3, 4.0, 'C')],
             dtype=[('x', int), ('y', float), ('z', 'U1')])
print(Z)


[(1, 2., 'A') (2, 3., 'B') (3, 4., 'C')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [116]:
Z = np.random.rand(1000000)

# Method 1: Using **
Z1 = Z ** 3

# Method 2: Using np.power
Z2 = np.power(Z, 3)

# Method 3: Element-wise multiplication
Z3 = Z * Z * Z

print(np.allclose(Z1, Z2) and np.allclose(Z2, Z3))  # Should return True


True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [117]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

matches = [np.all(np.isin(row, B), axis=1) for row in A]
matching_rows = A[np.any(matches, axis=0)]
print(matching_rows)


AxisError: axis 1 is out of bounds for array of dimension 1

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [118]:
A = np.random.randint(0, 5, (10, 3))
unequal_rows = A[(A[:, 0] != A[:, 1]) | (A[:, 1] != A[:, 2])]
print(unequal_rows)


[[2 3 3]
 [0 2 2]
 [2 4 3]
 [3 3 2]
 [3 4 2]
 [2 4 0]
 [3 0 2]
 [4 3 3]
 [0 3 4]
 [1 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [119]:
Z = np.array([0, 1, 2, 3, 4, 5])
binary_matrix = ((Z[:, None] & (1 << np.arange(8))) > 0).astype(int)
print(binary_matrix)


[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [120]:
A = np.random.randint(0, 5, (10, 3))
unique_rows = np.unique(A, axis=0)
print(unique_rows)


[[0 1 3]
 [1 0 2]
 [1 1 0]
 [1 1 2]
 [2 0 1]
 [2 0 4]
 [3 2 2]
 [4 3 0]
 [4 3 3]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [121]:
A = np.random.rand(3)
B = np.random.rand(3)

inner = np.einsum('i,i->', A, B)  # Equivalent to np.inner(A, B)
outer = np.einsum('i,j->ij', A, B)  # Equivalent to np.outer(A, B)
summation = np.einsum('i->', A)  # Equivalent to np.sum(A)
multiplication = np.einsum('i,i->i', A, B)  # Element-wise multiplication

print(inner, outer, summation, multiplication)


1.423013945319282 [[0.31503091 0.39844934 0.26093149]
 [0.49470307 0.62569768 0.40974904]
 [0.58227848 0.73646257 0.48228535]] 1.9680270790144765 [0.31503091 0.62569768 0.48228535]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [122]:
X = np.linspace(0, 10, num=10)
Y = np.sin(X)

from scipy.interpolate import interp1d

f = interp1d(X, Y, kind='linear')
X_new = np.linspace(0, 10, num=50)
Y_new = f(X_new)

print(Y_new)


[ 0.          0.16460673  0.32921346  0.49382019  0.65842692  0.82303365
  0.88588892  0.86734302  0.84879711  0.83025121  0.81170531  0.77510193
  0.59403883  0.41297572  0.23191262  0.05084951 -0.13021359 -0.28531276
 -0.42742995 -0.56954714 -0.71166433 -0.85378152 -0.95210424 -0.89714627
 -0.8421883  -0.78723033 -0.73227236 -0.6773144  -0.51663684 -0.32575368
 -0.13487052  0.05601263  0.24689579  0.41229082  0.5267096   0.64112837
  0.75554715  0.86996592  0.98438469  0.91767059  0.82831488  0.73895917
  0.64960345  0.56024774  0.4245137   0.23080673  0.03709977 -0.15660719
 -0.35031415 -0.54402111]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [123]:
X = np.random.randint(0, 5, (10, 5))
n = 10
valid_rows = X[np.sum(X, axis=1) == n]
print(valid_rows)


[[2 2 0 2 4]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [124]:
X = np.random.rand(1000)

N = 1000
means = np.array([np.mean(np.random.choice(X, size=X.shape[0], replace=True)) for _ in range(N)])

ci_lower, ci_upper = np.percentile(means, [2.5, 97.5])
print(f"95% confidence interval: ({ci_lower}, {ci_upper})")


95% confidence interval: (0.4829937727683307, 0.519154503832487)
